- {{cookiecutter.project_slug}}/docker-compose.yml
- {{cookiecutter.project_slug}}/docs/source/conf.py
- {{cookiecutter.project_slug}}/docs/source/configuration.rst
Also replaced references to emu by cookiecutter slug.
I think this closes issue #1 for now. Doc building works out of the box.
> commented ext_autodoc in docs conf until it is released in pywps

- {{cookiecutter.project_slug}}/tests/test_wps_caps.py
- {{cookiecutter.project_slug}}/tests/test_wps_inout.py
- {{cookiecutter.project_slug}}/tests/test_wps_sleep.py
- {{cookiecutter.project_slug}}/tests/test_wps_wordcounter.py
- {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/processes/__init__.py
- {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/processes/wps_sleep.py
This PR is a contribution to #3.
Changes:
* Added a `sleep` process from Emu (#3)
* Fixes imports in tests after moving tests folder (#17)
See: #3 and #17.
> add sleep process (#3)

- README.rst
- {{cookiecutter.project_slug}}/docs/source/conf.py
- {{cookiecutter.project_slug}}/docs/source/index.rst
- {{cookiecutter.project_slug}}/docs/source/processes.rst
- {{cookiecutter.project_slug}}/requirements.txt
- {{cookiecutter.project_slug}}/rtd.txt
This PR fixes #37.
Changes:
* Enabled pywps autodoc extension in Sphinx `conf.py`.
* Added `rtd.txt` requirements for readthedocs.
* Added process documentation.
> Fix #37: Enable pywps autodoc extension

- {{cookiecutter.project_slug}}/Makefile
This PR fixes #39.
Changes:
* Set APP_NAME in Makefile using cookiecutter.
> Fix #39: set app_name in Makefile

- {{cookiecutter.project_repo_name}}/Makefile
This PR fixes #45.
Changes:
* Use `conda` command available in path.
* Check if conda is available or fail.
* Don't install conda by itself in default path `~/anaconda`.
> use check_conda (#45)

- {{cookiecutter.project_repo_name}}/Makefile
While it might be preferable to ignore errors during portions of the buildout phase, it would be good to loudly raise errors during the testing phase.
Removed the hyphens (`-`) before `make test`, `make testall`, and `make pep8`. 
Links to other issues or sources.
> Raise makefile errors

- {{cookiecutter.project_repo_name}}/Makefile
- {{cookiecutter.project_repo_name}}/docs/source/dev_guide.rst
This PR fixes #64.
Changes:
* Added `make spec` target.
* Updated dev guide.
* Install additional packages `gunicorn` and `psycopg2` needed by Ansible deployment.
> added "make spec"

- .travis.yml
- README.rst
- environment.yml
- {{cookiecutter.project_repo_name}}/.travis.yml
- {{cookiecutter.project_repo_name}}/Makefile
- {{cookiecutter.project_repo_name}}/environment.yml
- {{cookiecutter.project_repo_name}}/setup.py
- {{cookiecutter.project_repo_name}}/{{cookiecutter.project_slug}}/cli.py
- {{cookiecutter.project_repo_name}}/{{cookiecutter.project_slug}}/processes/wps_say_hello.py
This PR fixes #67.
Changes:
* Skip conda-forge
* Skip python 2.7 support
* Skip six
* Added Python 3.7 tests
* pep8
* update readme
* Added "restart" target to Makefile
Fix #67.
> Fix 67 simplify

- {{cookiecutter.project_repo_name}}/.travis.yml
This PR fixes a conda issue on travis. `conda update conda` failed because `setuptools` was not installed.
Changes:
* Added `conda install setuptools` to travis config.
https://github.com/bird-house/hummingbird/pull/34
> added setuptools to conda env

- {{cookiecutter.project_repo_name}}/.github/CONTRIBUTING.md
- {{cookiecutter.project_repo_name}}/README.rst
This PR adds links to the dev-guide in the Readme to make the release with bumpversion more visible.
It fixes also the links in `CONTRIBUTING.md`
See discussion in FlyingPigeon PR:
https://github.com/bird-house/flyingpigeon/pull/300
Taken xarray readme as example:
https://github.com/pydata/xarray/blob/master/README.rst
> updated links to dev guide

- environment.yml
This PR updates the conda env to handle the latest cookiecutter release (1.7.0). It uses only conda packages to automatically resolve dependencies. Before `pip` installation for `pytest-cookies` failed due to cookiecutter dependency.
> fix conda env

- {{cookiecutter.project_repo_name}}/Makefile
- {{cookiecutter.project_repo_name}}/docs/source/conf.py
project repo Makefile: do not execute xdg-open since it hangs in TravisCI build
project repo docs conf: do not execute notebooks because we use mock imports
Those are backports from Raven PR https://github.com/Ouranosinc/raven/pull/272
> Backport fixes from Raven PR

- README.rst
- {{cookiecutter.project_repo_name}}/.travis.yml
- {{cookiecutter.project_repo_name}}/environment-docs.yml
- {{cookiecutter.project_repo_name}}/requirements_dev.txt
- {{cookiecutter.project_repo_name}}/setup.cfg
This PR fixes https://github.com/bird-house/cookiecutter-birdhouse/issues/61.
This PR is a continuation of PR https://github.com/bird-house/cookiecutter-birdhouse/pull/85.
Raven PR https://github.com/Ouranosinc/raven/pull/276 matching this PR.
Changes:
* Added documentation to use cruft initially to generate the project and after the fact to keep project in sync with cookiecutter template update.
* Fix missing bump version config for new `.cruft.json` file.
* Prevent merge conflicts on future cookiecutter template refresh in `requirements_dev.txt`.
* Add `make test-notebooks` to TravisCI.
> Doc how to use cruft and template improvement

- {{cookiecutter.project_repo_name}}/Dockerfile
- {{cookiecutter.project_repo_name}}/environment.yml
This PR fixes #91.
Changes:
* Enabled conda-forge channel in conda `environment.yml`.
* Restricted python version ... pywps async mode does not work on python 3.8.
* Docker conda env installs pywps only.
#91
PyWPS issue with multiprocessing on Python 3.8:
https://github.com/geopython/pywps/issues/508
> fix conda env and docker build

- {{cookiecutter.project_repo_name}}/Dockerfile
- {{cookiecutter.project_repo_name}}/environment.yml
This PR fixes the dockerfile in the template.
Changes:
* Fixed the conda version spec for pywps.
PR #92.
> fix dockerfile

- {{cookiecutter.project_repo_name}}/.travis.yml
So all new dev branches are built automatically without having to either
manually add the branch name to .travis.yml or being forced to create a
PR.
This creates redundant build on the same commit when PR is created but
otherwise no other harms.
No redundant build on PR merge since a brand new commit is created for
both merge commit or squash commit scenario.
See discussion
https://github.com/Ouranosinc/raven/pull/292#discussion_r460044455
> travis-ci: build all branches instead of only master

- README.rst
- {{cookiecutter.project_repo_name}}/.readthedocs.yml
- {{cookiecutter.project_repo_name}}/.travis.yml
- {{cookiecutter.project_repo_name}}/Makefile
- {{cookiecutter.project_repo_name}}/docs/Makefile
- {{cookiecutter.project_repo_name}}/docs/source/conf.py
- {{cookiecutter.project_repo_name}}/requirements_dev.txt
- {{cookiecutter.project_repo_name}}/setup.cfg
Currently, autodoc failure are treated as warnings only, resulting in
empty processes list, see
https://pavics-sdi.readthedocs.io/projects/raven/en/latest/processes.html.
This fix will turn these warnings into build failure on RtD and on
Travis-CI so we can catch those errors earlier.
Right now these warnings are falling silently !
Also changed Travis-CI config so it also builds Epub and Latex format as RtD to catch RtD errors before PR is merged.
Common fixes for those warnings are backported here.
Bonus we also catch nonexisting document reference and missing reference
in toctree, see below sample Raven warnings during docs build.
Raven succesful build logs with warnings on RtD:
https://readthedocs.org/api/v2/build/11487109.txt …
> fix empty autodoc processes list silent docs build failure

- {{cookiecutter.project_repo_name}}/requirements_dev.txt
The newest major release of pytest (6.0.0) is now compatible with nbval at and above 0.9.6. No more need for specific pinned versions.
> require pytest 6.0 and nbval 0.9.6

- CHANGES.rst
- {{cookiecutter.project_repo_name}}/setup.cfg
> Replace `search` by `parse` in the bumpversion config for `docs/conf.py`

- {{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py
This PR adds the `outputpath` and `outputurl` settings to the `cli.py` file.
This is useful for local installations where you want to run a test server with Phoenix and WPS birds on a single server.
> Updated "cli.py" to include "outputpath" and "outputurl"

- {{cookiecutter.project_slug}}/Makefile
This PR fixes #105 and replaces #106 
Changes:
* Added a `test-notebooks-lax` recipe for testing that notebooks run without comparing outputs
#105
This is currently implemented in `finch`.
> add nbval-lax-based testing target
